# Generated by Django 5.2.1 on 2025-05-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopLevelDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=255)),
                ('name_official', models.CharField(max_length=255)),
                ('cca2', models.CharField(max_length=3)),
                ('cca3', models.CharField(max_length=3)),
                ('ccn3', models.CharField(blank=True, max_length=10, null=True)),
                ('cioc', models.CharField(blank=True, max_length=10, null=True)),
                ('independent', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('un_member', models.BooleanField(default=False)),
                ('fifa', models.CharField(blank=True, max_length=10, null=True)),
                ('population', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('landlocked', models.BooleanField(default=False)),
                ('flag_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_png', models.URLField(blank=True, null=True)),
                ('flag_svg', models.URLField(blank=True, null=True)),
                ('flag_alt', models.TextField(blank=True, null=True)),
                ('start_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('map_google', models.URLField(blank=True, null=True)),
                ('map_openstreet', models.URLField(blank=True, null=True)),
                ('continents', models.CharField(blank=True, max_length=100, null=True)),
                ('borders', models.ManyToManyField(blank=True, to='countries.country')),
                ('currencies', models.ManyToManyField(blank=True, related_name='countries', to='countries.currency')),
                ('languages', models.ManyToManyField(blank=True, related_name='countries', to='countries.language')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='countries.region')),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitals', to='countries.country')),
            ],
        ),
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latlng', to='countries.country')),
            ],
        ),
        migrations.CreateModel(
            name='Subregion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='countries.region')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='countries.subregion'),
        ),
        migrations.AddField(
            model_name='country',
            name='timezones',
            field=models.ManyToManyField(blank=True, related_name='countries', to='countries.timezone'),
        ),
        migrations.AddField(
            model_name='country',
            name='tlds',
            field=models.ManyToManyField(blank=True, related_name='countries', to='countries.topleveldomain'),
        ),
    ]
